<!DOCTYPE html>
<html>
<body>
	<section class="regular slider">
		<div>
			<img src="http://placehold.it/350x300?text=1" />
		</div>
		<div>
			<img src="http://placehold.it/350x300?text=2" />
		</div>
		<div>
			<img src="http://placehold.it/350x300?text=3" />
		</div>
		<div>
			<img src="http://placehold.it/350x300?text=4" />
		</div>
		<div>
			<img src="http://placehold.it/350x300?text=5" />
		</div>
		<div>
			<img src="http://placehold.it/350x300?text=6" />
		</div>
	</section>
</body>
</html>